# Generated by Django 2.1.7 on 2019-03-30 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_publica', models.BooleanField(blank=True, null=True)),
                ('evento', models.CharField(max_length=128, verbose_name='evento')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('compromisso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicar', models.BooleanField(blank=True, null=True)),
                ('evento', models.CharField(max_length=128, verbose_name='evento')),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agenda.Pessoa'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agenda.Pessoa'),
        ),
    ]
